annotations:
  catalog.cattle.io/auto-install: rancher-eks-operator-crd=match
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/kube-version: '>= 1.33.0-0 < 1.36.0-0'
  catalog.cattle.io/namespace: cattle-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux,windows
  catalog.cattle.io/provides-gvr: eksclusterconfigs.eks.cattle.io/v1
  catalog.cattle.io/rancher-version: '>= 2.14.0-0 < 2.15.0-0'
  catalog.cattle.io/release-name: rancher-eks-operator
  catalog.cattle.io/scope: management
apiVersion: v2
appVersion: 1.14.0-rc.2
description: A Helm chart for provisioning EKS clusters
home: https://github.com/rancher/eks-operator
name: rancher-eks-operator
sources:
- https://github.com/rancher/eks-operator
version: 1.14.0-rc.2
